public class ValueConstant {
    public static string CERTIFICATE_PATH = "/home/sushil/Documents/certificate/Dev/test/test-crt-dev.pem";
    public static string ACCESS_TOKEN = "bd7e7b2440c8499288d4390b13896067";
    public static string MERCHANT_ID = "test";
    public static string CUSTOMER_ID = "CUS1234";
    public static string TRANSACTION_AMOUNT = "19.99";
    public static string SUCCESS_URL = "https://pay.newgenpayments.com/client/html/Success.html";
    public static string FAIL_URL = "https://pay.newgenpayments.com/client/html/Fail.html";
    public static string CANCEL_URL = "https://pay.newgenpayments.com/client/html/Cancel.htm";
    public static string CUSTOMER_FIRST_NAME = "Foo";
    public static string CUSTOMER_LAST_NAME = "Bar";
    public static string CUSTOMER_MOBILE_NUMBER = "31-232567456";
    public static string CUSTOMER_EMAIL = "foo@baz.com";
    public static string MERCHANT_NAME = "qux";
    public static string MERCAHNT_EMAIL = "qux@corge.com";
    public static string MERCHANT_MOBILE_NUMBER = "1234567890";
    public static string CARD_HOLDER_NAME = "Grault";
    public static string CARD_NUMBER = "4666300411032500282";
    public static string CVV = "123";
    public static string EXPIRY_MONTH = "10";
    public static string EXPIRY_YEAR = "2030";
    public static string TIMEZONE = "330";
    public static string BROWSER_COLOR_DEPTH = "24";
    public static string BROWSER_LANGUAGE = "en-GB";
    public static string BROWSER_SCREEN_HEIGHT = "1080";
    public static string BROWSER_SCREEN_WIDTH = "1920";
    public static string OS = "windows";
    public static string BROWSER_ACCEPT_HEADER = "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*";
    public static string USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36";
    public static string BROWSER_JAVASCRIPT_ENABLED = "false";
    public static string BROWSER_JAVA_ENABLED = "true";
    public static string ACCEPT_CONTENT = "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3";
    public static string BROWSER_IP = "192.1.1.1";
    public static string FROM_DATE = "2023-04-17";
    public static string TO_DATE = "2023-04-19";
    public static string FROM_COUNT = "0";
    public static string LIMIT = "100";
    public static string WEBHOOK_ENDPOINT = "http://www.example.com";
    public static string SUBSCRIPTION_PERIOD = "WEEK";
    public static string SUBSCRIPTION_FREQUENCY= "2";
    public static string SUBSCRIPTION_TOTAL_INSTALLMENTS = "1";
    public static string SUBSCRIPTION_TYPE = "1";
    public static string SUBSCRIPTION_CODE = "BBB";
    public static string SUBSCRIPTION_NAME = "Video Streaming Service Plan";
    public static string SUBSCRIPTION_APPLY_DATE = "2021-07-14";
    public static string SUBSCRIPTION_START_DATE = "2020-07-24";
    public static int SUBSCRIPTION_QUANTITY = 1;
}